#!/usr/bin/env python3
"""
Flatten a subproject into a single Markdown file in the workspace root.

Given a project subfolder (e.g. "Breaking the Beasts"), concatenates every
`.md` file inside it into one file named after the project
(e.g. `breakingthebeasts.md`) in the parent/workspace root.

Heading hierarchy in the combined file:

    # <immediate-directory>     <- one per leaf directory that holds .md files
                                   (e.g. "characters", "brainstorm" — not "kb/characters")
    ## ...                      <- each file's OWN headings, demoted by 1, capped at ####

So a heading that is `#` inside a source file becomes `##` in the output;
`##` becomes `###`; `###` and deeper all cap at `####`. Headings inside
fenced code blocks (``` or ~~~) are left untouched.

Root-level files (directly in the project folder) are included but get no
group header. Filenames are not emitted as headers.

Sections are ordered by SECTION_ORDER (a sensible reading order); sections not
listed there sort after the listed ones, alphabetically. Root-level files sort
last.

Two files are written per run:
    exports/<slug>.md      clean, user-facing snapshot
    exports/<slug>.ai.md   same content plus `<!-- source: <path> -->` comments
                           and a read-only header, for muse to load as cheap
                           session context and trace each passage to its file

Both are derived artifacts — the individual project files remain the source of
truth. Never edit the exports; they are regenerated on every save.

Usage:
    python3 scripts/flatten_project.py "Breaking the Beasts"
    python3 scripts/flatten_project.py "Breaking the Beasts" --output custom.md

Run from anywhere; paths resolve relative to the workspace root (the parent
of this script's directory).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

WORKSPACE_ROOT = Path(__file__).resolve().parent.parent

HEADING_RE = re.compile(r"^(#{1,6})(\s.*)$")
FENCE_RE = re.compile(r"^\s*(`{3,}|~{3,})")

# Directories inside a project we never fold in.
SKIP_DIRS = {".git", ".claude", "node_modules", "__pycache__"}

# Reading order for the flattened snapshot, keyed by the leaf directory name
# that holds the .md files (e.g. "characters" for kb/characters/*.md). Sections
# not listed here sort after all listed ones, alphabetically by leaf name.
SECTION_ORDER = [
    "outline",
    "timeline",
    "story",
    "drafts",
    "brainstorm",
    "characters",
    "world",
    "canon",
    "styles",
    "issues",
    "samples",
]


def slugify(name: str) -> str:
    """'Breaking the Beasts' -> 'breakingthebeasts'."""
    return re.sub(r"[^a-z0-9]", "", name.lower())


def demote_body(text: str, levels: int = 1) -> str:
    """Push every ATX heading down by `levels`, capped at 4. Skip code fences."""
    out: list[str] = []
    in_fence = False
    fence_marker = ""
    for line in text.splitlines():
        fence = FENCE_RE.match(line)
        if fence:
            marker = fence.group(1)[0]  # ` or ~
            if not in_fence:
                in_fence, fence_marker = True, marker
            elif marker == fence_marker:
                in_fence, fence_marker = False, ""
            out.append(line)
            continue
        if not in_fence:
            m = HEADING_RE.match(line)
            if m:
                new_level = min(len(m.group(1)) + levels, 4)
                out.append("#" * new_level + m.group(2))
                continue
        out.append(line)
    return "\n".join(out)


def collect_md_files(project_dir: Path) -> list[Path]:
    files = [
        p
        for p in project_dir.rglob("*.md")
        if not any(part in SKIP_DIRS for part in p.relative_to(project_dir).parts)
        and p.name not in {"CLAUDE.md", "README.md"}
    ]
    # Sort by section reading order (SECTION_ORDER), then by leaf directory
    # name for unlisted sections, then filename. Root-level files sort last.
    def key(p: Path):
        rel = p.relative_to(project_dir)
        leaf = rel.parent.name if str(rel.parent) != "." else ""
        try:
            rank = SECTION_ORDER.index(leaf)
        except ValueError:
            rank = len(SECTION_ORDER)
        return (rank, leaf.lower(), rel.name.lower())

    return sorted(files, key=key)


AI_HEADER = (
    "<!-- EXPORT SNAPSHOT — for Claude/muse to load as cheap session context.\n"
    "     READ-ONLY. Do NOT edit this file; it is regenerated on every save.\n"
    "     Headings are demoted 1 level: ## here == # in the source file.\n"
    "     To change something, open the individual file named in the nearest\n"
    "     `<!-- source: ... -->` comment above the passage and edit THAT file.\n"
    "     Never copy heading levels from here into the source files. -->"
)


def build(project_dir: Path, project_name: str, annotated: bool = False) -> str:
    """Concatenate the project's .md files.

    When `annotated` is True, prepend an AI-facing header and emit a
    `<!-- source: <relative-path> -->` comment before each file's body so the
    reader knows exactly which individual file to edit. The plain (unannotated)
    build is the clean, user-facing snapshot.
    """
    lines: list[str] = []
    if annotated:
        lines.append(AI_HEADER)
        lines.append("")

    current_group = object()  # sentinel so the first file always checks for a header
    for path in collect_md_files(project_dir):
        rel = path.relative_to(project_dir)
        # Use only the immediate parent dir name; root-level files have no group.
        group = rel.parent.name if str(rel.parent) != "." else None
        if group != current_group:
            if group:
                lines.append(f"# {group}")
                lines.append("")
            current_group = group
        if annotated:
            lines.append(f"<!-- source: {rel.as_posix()} -->")
            lines.append("")
        body = path.read_text(encoding="utf-8").strip("\n")
        lines.append(demote_body(body))
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description="Flatten a subproject into one .md file.")
    ap.add_argument("project", help="Project subfolder name, e.g. 'Breaking the Beasts'")
    ap.add_argument("--output", help="Override output filename (default: <slug>.md)")
    args = ap.parse_args()

    project_dir = (WORKSPACE_ROOT / args.project).resolve()
    if not project_dir.is_dir():
        print(f"error: project folder not found: {project_dir}", file=sys.stderr)
        return 1
    if WORKSPACE_ROOT not in project_dir.parents:
        print("error: project must live directly under the workspace root", file=sys.stderr)
        return 1

    exports_dir = WORKSPACE_ROOT / "exports"
    exports_dir.mkdir(exist_ok=True)
    out_name = args.output or f"{slugify(project_dir.name)}.md"
    out_path = exports_dir / out_name
    # AI-annotated sibling: <name>.md -> <name>.ai.md
    ai_path = out_path.parent / f"{out_path.stem}.ai.md"

    # Clean, user-facing snapshot (no AI notes).
    content = build(project_dir, project_dir.name)
    out_path.write_text(content, encoding="utf-8")
    # Annotated snapshot muse loads: source-path comments + read-only header.
    ai_content = build(project_dir, project_dir.name, annotated=True)
    ai_path.write_text(ai_content, encoding="utf-8")

    n_files = len(collect_md_files(project_dir))
    print(
        f"wrote {out_path.relative_to(WORKSPACE_ROOT)}  ({n_files} files, {len(content):,} chars)\n"
        f"wrote {ai_path.relative_to(WORKSPACE_ROOT)}  (annotated, {len(ai_content):,} chars)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
